### ISSUE TITLE
Verify that REDIS is the way to go

### ISSUE THREAD

**Issue by qjhart** [CSTARS/cimis-mobile#1]
With our new experience with other streaming data tools, it's worth looking back at our original REDIS implementation to decide if it's the correct idea.  I think it is, but I think it's worth a quick comparison.

**Comment by jrmerz** [comment]
Could use some sample data for this.  I think compatibility comes into play as well. Firebase now allows for full app hosting, but, you are building around the firebase architecture and have to pay costs, which can get expensive.  

Suggestions of architecture we should look into?  I think knowing the final resting place constraints will play a large role in this.

**Comment by qjhart** [comment]
Well, we have all the sample data we need.  Part of the existing repo has the load2redis script that creates the JSON (redis style) that we plan to use for the project.  Looking at that, it looks like it's not complete :) but the basics are there for pulling the data from CIMIS.  I should check clould9 and see if I left an uncommited update.

**Comment by qjhart** [comment]
Regarding arch. see #2

**Comment by qjhart** [comment]
Superceded by #5
