### ISSUE TITLE
Aggregations

### ISSUE THREAD

**Issue by qjhart** [CSTARS/cimis-mobile#10]
We have convinced DWR to replace Zipcodes with DAU / County bourndaries. This is good, because they do not change.  We need to add a new component to the REDIS server to store these DAU-County data.  These are aggregations of a number of CIMIS pixels.  I suggest we have a database, (Second REDIS? or just seperate keys (I like that better).

Example aggregations
[aggregates.zip](https://github.com/CSTARS/cimis-mobile/files/394846/aggregates.zip)

``` js
aggregates={
  "6-29": {
    "Z8": "100"
  },
  "6-30": {
    "Z8": "100",
    "DAU014": "62"
  },
  "6-31": {
    "Z8": "100",
    "DAU014": "94"
  },
...
```

Which is an object for each CIMIS pixel, of the overlapping DAUs, and ETO_zones and the percentage they overlap (by pixel).  Then, at every day.  For each pixel, get list of Daus, add ETo*area,

``` js
var allRegions={};
pixels.forEach(pix => {
  regions = aggregate[pixel];
  region.forEach(r => {
     var this_region = typeof allRegions[r] === 'undefined' ? {} : allRegions[r];
    this_region.et += pix.ET * r.Area;
     this_region.area +=  r.Area;
  }
}
// All pixels processed.  Get average value
allRegions.forEach(r => {
  r.et = r.et/r.area
});
```

These are what go to REDIS.  Can be all values of course

``` json
allRegions = {
 "Z8" : {"et":1.65,"area":360},
 "DAU014":{"et":2.4,"area":100}
};
```

**Comment by qjhart** [comment]
```{js}
daus = {
 dau1 : [{pixel:32,area:89},...]
}
```

**Comment by jrmerz** [comment]
@qjhart seems reasonable.  How are we calculating the DAU per pixel?  Also, shouldn't then dau at to 1?   Your example is over 100%, if I am understanding this correctly.

**Comment by qjhart** [comment]
@jrmerz No, the values are the percentage for each pixel, so we need to add up those percentages as well.  Let's us know the size of each region as well.

**Comment by jrmerz** [comment]
Sample ETo Region functionality is up: https://cimis-mobile.casil.ucdavis.edu

**Comment by qjhart** [comment]
@jrmerz Updated ETo Zone maps, at: https://github.com/CSTARS/eto-zone-maps/releases/tag/v1.0-beta
Or at : https://github.com/CSTARS/eto-zone-maps,  fft.js code at: https://github.com/CSTARS/eto-zone-maps/blob/master/fft/fft.js
 DAU-CO at: https://github.com/ucd-cws/dwr-dau/releases/tag/v2.1.0

**Comment by qjhart** [comment]
Here is the color scheme Mui used.  Goes from lowest ET to highest.
![eto_zones_mod](https://cloud.githubusercontent.com/assets/344953/17457081/65a7225a-5ba1-11e6-9478-3e60a27dd316.png)

**Comment by jrmerz** [comment]
@qjhart can you add some comments for the input/output variables in:  https://github.com/CSTARS/eto-zone-maps/blob/master/fft/fft.js

eg: return({e:E,d:D,re:re,im:im}) ?
