### ISSUE TITLE
Explore (ET/DAU) Zones - Map Issues

### ISSUE THREAD

**Issue by qjhart** [CSTARS/cimis-mobile#11]
- [ ] The map component on the individual zones, needs to zoom to the proper spot.  This was working great before.  
- [x] It would be better IMO if the map on these individual pages did not capture gestures, so mobile users could scroll to the data.
- [x] Please make the layers a little less opaque.

**Comment by jrmerz** [comment]
updates live

**Comment by qjhart** [comment]
It is okay to zoom to the selected zone.

**Comment by jrmerz** [comment]
w/o panning controls or gestures, you would then be stuck.

**Comment by jrmerz** [comment]
updated.
