### ISSUE TITLE
Add station data to Ring Buffer

### ISSUE THREAD

**Issue by jrmerz** [CSTARS/cimis-mobile#12]
The CIMIS data has been updated to include more information in the station.csv data.  In particular, for example; http://cimis.casil.ucdavis.edu/cimis/2016/12/07/station.csv includes all data required by the ring buffer.   The cron job for the ring buffer needs to download the csv files, and add a new set of values.  Let's say ST006 for Davis (st_number 6)  The data them selves have the GIS location if we  don't want to store seperately.  but we can do that too.

**Comment by jrmerz** [comment]
TODOS
- Verify units are constant
- crosswalk to cimis to spatial cimis terms.
- workflow on when to contact the cimis station data api

**Comment by qjhart** [comment]
These data come directly from the et.cimis.ca.gov website, and conform to the Spatial CIMIS data [descriptions](http://wwwcimis.water.ca.gov/Resources.aspx).  We use the metric units.  Each value includes a [Quality Flag](https://docs.google.com/viewer?url=http%3A%2F%2Fwwwcimis.water.ca.gov%2FContent%2FPDF%2FCurrentFlags2.pdf)

| parmeter | unit | value | crosswalk
| --- | --- | --- | --- |
x,y,z | (m) | EPSG (x,y) and elevation (z) | x,y
date | |
day_asce_eto | mm | 
day_precip | mm | 
day_sol_rad_avg | W/m^2 |
day_vap_pres_avg | kPa |
day_air_tmp_max | C |
day_air_tmp_min | C |
day_air_tmp_avg | C |
day_rel_hum_max | % |
day_rel_hum_min | % |
day_rel_hum_avg | % |
day_dew_pnt | C |
day_wind_spd_avg | m/s |

**Comment by jrmerz** [comment]
@qjhart can you fill in table above with display labels

**Comment by jrmerz** [comment]
@qjhart as of this commit 967c1d9345b331f460352813f0375caa70d92a70 the new version of the app is ready to go.  Issue is cimis-mobile.casil.ucdavis.edu doesn't have docker (and doesn't support it).  Thoughts for deployment?
