### ISSUE TITLE
Marshal a DWR server for the cimis-mobile server

### ISSUE THREAD

**Issue by qjhart** [CSTARS/cimis-mobile#15]
The CIMIS Mobile Application requires only the smallest set of services for deployment at DWR.  The minimum requirement is something like a 15Gb  (4Gb mem 2 core) linux machine to run the service, and that's might be overkill.  We need SSH access to the machine for installation of the software.  The most simple approach would be to run an apache service, and docker on that server, and we would replicate the UCD setup exactly. 

This system could be added before the Spatial CIMIS conversion of DWR is completed, if we can access the UCD server in the interium. 

Tthe cimis-mobile could also be hosted on the same machine that hosts the public directories of the final CIMIS data products.  If that's a linux computer, and we can add docker to that, that's a great solution.  I can't find the public name for that machine.

# Complete

This task is complete when qhart and gscheer have accounts and sudo access to this machine, with the SSH keys that we use to access the cimis servers.    The machines need access to the outside world to get access to specifically github and docker repositories.  The machines will also need access to the DWR public CIMIS location to get data, and the apache web service needs to be publically available.

**Comment by gjscheer-ucd** [comment]
The minimum specs for this DWR cimis-mobile VM would be:
1 CPU, 2GB RAM and 15GB disk
The suggested specs are:
2 CPU, 4GB RAM and 25GB disk

Ubuntu 16.07 LTS is ideal.  **Ports 80 and 443 should be publicly available**.

**Comment by ajdelmundo** [comment]
Quinn / George,

The servers listed below have been provisioned in the non-production environment for deploying the CIMIS mobile app for testing purposes.  They both meet the minimum specs except for the OS (Red Hat and not Ubuntu).  Both you and George should have sudo permissions for your accounts (qhart and gscheer).  Your public keys have also been added for SSH access.  Please verify and let me know if there are any issues.

** Non-Production Environment Servers **
-> dwrnprhapp0074 (Dev environment)
-> dwrnprhapp0076 (Test environment)

**Comment by gjscheer-ucd** [comment]
I can confirm that I have ssh access to cimis@dwrnprhapp0074 and cimis@dwrnprhapp0076 with my public key.  However the following issues remain:

1) I cannot verify if Quinn also has access.  
2) I cannot sudo to root since I do not know the local cimis account password or I’m not in the proper security group
3) I cannot confirm if ports 80/443 are publicly available

**Comment by qjhart** [comment]
We received notice on Jan 2, 2017 that qjhart and gjscheer now have sudo access to these to machines.   
- qhart has access to both machines.  The development machine was setup for his DWR ssh-keys, while the testing machine wasn't.  qjhart's password works on both machines.

I tried to start developing on the dev server.   My first effort was to get git and docker installed.

```bash 
# Use updated package manager
yum install dnf
yum remove dnf
yum install git emacs-nox docker docker-compose 
# At this point I have docker-compose version 1.9 and docker version 1.12
systemctl start docker.service  # This works too
```
I think that these are maybe okay.   This docker version `docker info` uses the old devicemapper storage setup.  Most installations have moved to another storage backend, and that's not encouraged for production.  

My next step was to try and clone the github repository over to the dev machine.  

``` bash
 git clone https://github.com/CSTARS/cimis-mobile.git
```
This doesn't seem to work since the development machine doesn't have access out via 80 and 443.  Additionally, I tried to setup a remote port forwarding system via putty, but the event logs say that the remote host has disabled port forwarding. 

While I'm unsure about whether those versions of docker will work, I do know I'll need git and emacs on the testing machine, so I tried installing those, and running the same tests.  I have the same problems with that machine.

**Comment by qjhart** [comment]
@ajdelmundo, Does DWR have a methodology in place for running docker? 
@qjhart docker is new technology for DWR.  The CIMIS mobile app will be the first to run it

**Comment by qjhart** [comment]
DWR will not be hosting this application.
