### ISSUE TITLE
Setup @start crontab entry

### ISSUE THREAD

**Issue by qjhart** [CSTARS/cimis-mobile#17]
I've verifed with Justin, that  the application server itself does normal updates.  So we only need a crontab for the startup.  I suggest that we make a new user cimis, and run it normally as that user.  We can put the app in /home/cimis as well. 

We can stay in that group for access, and we can add our ssh-keys for direct access as well.  That's pretty much how cimis is run for the spatial-cimis app

**Comment by jrmerz** [comment]
all, just FYI, I have add really good luck using systemd with docker-compose:

```
[Unit]
Description=CIMIS Mobile
After=network.target docker.service

[Service]
Type=simple
WorkingDirectory=/path/to/app
ExecStart=/usr/local/bin/docker-compose -f /path/to/app/docker/docker-compose.yml up
ExecStop=/usr/local/bin/docker-compose -f /path/to/app/docker/docker-compose.yml down

[Install]
WantedBy=multi-user.target
```

then things start on boot, and you get `systemctl start cimis-mobile` / `systemctl stop cimis-mobile`

**Comment by jrmerz** [comment]
Wired up systemctl.  App should start on boot.  then use:

```sudo systemctl start cimis-mobile```
or
```sudo systemctl stop cimis-mobile```
