### ISSUE TITLE
Clean up apache setups

### ISSUE THREAD

**Issue by qjhart** [CSTARS/cimis-mobile#18]
- [x] Get a proper SSL cert for cimis-mobile.cstars.ucdavis.edu
- [x] Get a **WILDCARD** cert for goes.cstars.ucdavis.edu and will use that for all our services.

**Comment by qjhart** [comment]
@gjscheer-ucd I removed the issues above that are no longer relevant

**Comment by gjscheer-ucd** [comment]
Created a wildcard cert for goes.cstars.ucdavis.edu on cimis-mobile.cstars.ucdavis.edu.  Keys backed up to Box.
