### ISSUE TITLE
Cost out REDIS on Amazon

### ISSUE THREAD

**Issue by qjhart** [CSTARS/cimis-mobile#2]
We have a few methods of developing this application;
- [ ] Continue development on cloud9
- [ ] Develop on a tiny amazon EC instance with a Amazon REDIS backend
- [ ] Develop on a IET virtual machine

Which is best? Which has cleanest path to a situation where DWR wants to take the application over?
Where is the client?

**Comment by jrmerz** [comment]
I'm ok with cloud9 IDE ... really that is just a solution for development on the web.  I will still proly add grunt tasks for building and running app locally.

Cleanest or most compatible?  Depending on your definition of clean, I think a hosted solution would probably be the 'cleanest' but that might not be doable with DWR.  The simplest or most compatible would probably be a Ubuntu install with redis / express.  I'm assuming the client would be hosted on same machine, no?

**Comment by jrmerz** [comment]
Amazon's hosted solution, ElastiCache http://aws.amazon.com/elasticache is ~$140 per year under 1 year contract.

Remind me again why we wouldn't just self host Redis on the amazon instance?

**Comment by jrmerz** [comment]
Other solutions.   Firebase can host app and data for ~$600 per year ($50 per month).

**Comment by qjhart** [comment]
@jrmerz, with Elasticache, we'd need to have an Amazon AWS for the server as well correct?  The reason to not use a single instance I guess is that we could scale without managing making the backends consistant.  However, as Google notes, they are all in on containers, and only use those, so we could also think of a container solution on GCE or some other platform.  This would make ushave to make the backend consistent, but it maybe the cleanest way to move to DWR?

**Comment by qjhart** [comment]
Current REDIS example is now using redislabs as a test, which may run as low as $7/mo.

**Comment by qjhart** [comment]
Hard to beat local implementation in terms of upload speed.  Free REDIS labs version had speed governed at about 1 addition/200ms which made cloud based versions impractical.
