### ISSUE TITLE
Add Legends to Charts

### ISSUE THREAD

**Issue by qjhart** [CSTARS/cimis-mobile#20]
The graphs should match this  [reference chart](https://docs.google.com/spreadsheets/d/1EDyRBGSJ-qAmAHjh9D5dScX883UYzUa-5dwCEi7RAbI/edit?usp=sharing)

**Comment by qjhart** [comment]
This issue on hold until DWR responds with completed reference charts.  @jrmerz if it's worth selecting a good reference size for the  charts in this let me know. Alternatively, if it's better to move to a tab, so that we can preview the charts by looking at those tabs in small screens let me know that too.

**Comment by rtrezza** [comment]
The reference charts you have now are really close. However, we want the data points to be joined using straight lines (no spline like it is now). Precipitation should be represented as bars. Graph with multiple lines should have a legend for each data set. Scales should start in reasonable values (for example precipitation, solar radiation and relative humidity should start at 0). I am attaching an excel file with some examples to give an idea of the kind of graph we want.  You can adjust colors, size, etc to get a better look on the website. Your "example graphs" are good (with the legend on the top) but we only need the data showed in the attached graphs.xlsx. We do not need to show net longwave radiation, vapor pressure and other variables.  

[graphs.xlsx](https://github.com/CSTARS/cimis-mobile/files/1969131/graphs.xlsx)

**Comment by rtrezza** [comment]
In addition, we do need a graph for Vapor Pressure

**Comment by jrmerz** [comment]
updated charts pushed

**Comment by rtrezza** [comment]
The graphs looks much better now. The only thing I see that it might need some improvement is the display of the dates. Look this attached example where May 26 is not being displayed so it looks like that both P events occurred on May 25. Can we do something to improve it ?. If not, it can be Ok if data is also displayed on a tabular view
![precipitation](https://user-images.githubusercontent.com/13323649/40860324-d2e23716-6599-11e8-9aa4-035e688b82ce.JPG)

**Comment by rtrezza** [comment]
I see that other graphs (for example average DAU zone ETo) have values connected using fitting curves instead of straight lines. I am attaching an example. Could you plot the values using straight lines to connect them ?. Thanks   

![image](https://user-images.githubusercontent.com/13323649/40860820-a39a4096-659b-11e8-9eb4-fe8b39e1ac04.png)

**Comment by jrmerz** [comment]
@rtrezza the horizontal axis date labels are laid out by the charts library.  There isn't a lot I can do about that, but will see if there are any further tweaks that can be made.   As for the curved lines, please give a hard refresh, it doesn't look like you are seeing the latest version (you may need to clear your cache).

![screen shot 2018-06-01 at 1 01 29 pm](https://user-images.githubusercontent.com/1852393/40860994-392b04d8-659c-11e8-8d29-fda998cca617.png)

**Comment by rtrezza** [comment]
Now is OK. I deleted the comment about straight lines on the DAU ETo following your explanation. Thanks   
As I said before, if the data is also going to be displayed as a table, then we can live with the graph's dates as displayed now
