### ISSUE TITLE
Browser Issue - IE 11

### ISSUE THREAD

**Issue by qjhart** [CSTARS/cimis-mobile#22]
Application will not load in Internet Explorer

**Comment by jrmerz** [comment]
IE10? Not supported by polymer: https://www.polymer-project.org/2.0/docs/browsers.  I will add in a +1 million session per/year site like the library, there were 14 IE10 sessions. https://www.microsoft.com/en-us/windowsforbusiness/end-of-ie-support, https://support.microsoft.com/en-us/lifecycle/search?alpha=Internet%20Explorer

**Comment by jrmerz** [comment]
How about a banner to  IE < 11 saying upgrade IE?

**Comment by qjhart** [comment]
I think I mistyped 10 for 11.

**Comment by jrmerz** [comment]
Fixed with new loader and tweak to how shared styles are imported: 92e3579fcbf18dd2791dae3212254060227bb55d
