### ISSUE TITLE
Static description of the dwr-mobile app

### ISSUE THREAD

**Issue by qjhart** [CSTARS/cimis-mobile#3]
We have a test application, but we don't have a development document, (that I recall).  Should that be a simple Google Doc, or should we make that part of the dwr-mobile wiki?

**Comment by jrmerz** [comment]
Or gh-pages :)  Depending on level of theming you want, I would say live in github and either go with wiki or gh-pages.

**Comment by qjhart** [comment]
I guess in reality gh-pages is easier, but then we need to choose a framework.  Is this a Jekyll thing? Github's default?

**Comment by jrmerz** [comment]
I would actually argue wiki is easier.  With gh-pages, branch is just served over http, so you add whatever you want.  If you drop in a css theme that does a nice job of styling basic html elements (like ecosis docs) this can be relatively easy, but you are still hand writing html.

**Comment by qjhart** [comment]
@jrmerz then wiki?

**Comment by qjhart** [comment]
Wiki

**Comment by jrmerz** [comment]
With some overview documentation in the About tab of the app.
