### ISSUE TITLE
Port demo to polymer 0.8+

### ISSUE THREAD

**Issue by jrmerz** [CSTARS/cimis-mobile#4]
Polymer 0.9 just rolled out, guessing 1.0 is due out in two weeks at I/O.  The current app needs to get cycled over to 'new way of doing things' in polymer.  I will +1 for ES6 modules + browserify for all core logic.   My latest hammer / nail.

**Comment by qjhart** [comment]
Agreed.  That means we should probably work out what our _command_line_ implementation should look like.

**Comment by jrmerz** [comment]
I can start the project scaffold without the that.  But yes, proly soon need to start thinking about that.
