### ISSUE TITLE
User Demographics

### ISSUE THREAD

**Issue by qjhart** [CSTARS/cimis-mobile#8]
One requirement for the CIMIS mobile application is that we get some idea of the users of the system.  The original call was for users, which has thankfully been  tabled.  But we still need some short descriptive information.   My last suggestion was for a splash screen that would come up on the screen, asking a few questions.  This could be dismissed, but the app would keep bringing it up until the questions were answered, at which time I guess a local value would be saved, and the splash screen would stop.  

0) The form would go to the server, which would record them, making no attempt to disallow multiple additions, etc.  They could go the REDIS db, or to a google form.

There are additional possibilities as well:
1) Add google analytics to the application, recording access the home page
2) Record JSON calls to analytics
3) Record JSON calls locally (By incrementing REDIS variables)
4) Add analytics including a customer id which would  be what was stored locally by filling out the form

@jrmerz what do you think about the above?  I guess my feeling is that 1) and 3) would be worthwhile, but none of the others, 0) and 3) are better saved in REDIS, in a separate db. and maybe avoiding 1) woiuld be better for the state, IDK.

**Comment by jrmerz** [comment]
1 all the way.  Remember you can store arbitrary data in google analytics.  I would just create custom events for actions you wish to track.  You will not get as much bang for your buck with any other solution.

We can add a form.  But I would think about an incentive to make someone want to fill it out.  Keeping track of who has filled it out w/o accounts will be difficult as well.

**Comment by qjhart** [comment]
OK, you mean store the customer forms in analytics as well? 
And easier to store the grid access there as well? I wonder about that in terms of 
easily getting the stats out of that.  Eg a daily updated density of where users clicked would be nice, and easy to do with REDIS. 
We will make no attempt at tracking.  The incentive will be to eliminate the splash screen :)

I think the questions are simple and quick to answer: like

I use this application for:
[ ] farming
[ ] turf management
[ ] monitoring
[ ] research
[ ] fun

**Comment by jrmerz** [comment]
So I'm adding another form wired up to Google analytics?

**Comment by qjhart** [comment]
@jrmerz not another form, just use this form for the what is currently at the survey on the about section.  I have to admit, I tried to find that survey on the analytics page, and didn't have much luck.  The two graphs I would like to have are: 1) A pie chart showing the percentage of these different users that access the site, and 2) a heat map showing what they are accessing in the state, but both are out side the scope of this project.   If DWR can add their analytics to the app, they can build those out.
