### ISSUE TITLE
Scheduling Mobile App Data Import

### ISSUE THREAD

**Issue by jrmerz** [CSTARS/cimis-mobile#9]
Currently the mobile app is not aware of when the daily data is ready for import.  @qjhart has suggested a push from cimis.casil.ucdavis.edu.

**Comment by jrmerz** [comment]
I have created a cron to run at 3am and again at 6am (verification).  @qjhart when 'should' the data be ready?

Also, the app now requests the current dates in the db (using /cimis/dates) rather than assuming 'yesterday' is in the db.  When clicking the map, the most recent date in the db is looked at for 'most recent' ETo display.

Along with this, the utils/import.js script now gracefully fails and moves on if a date does not exist on cimis.casil.

**Comment by qjhart** [comment]
Earliest is 4am.  Then try 6am.

**Comment by jrmerz** [comment]
changed to 4am.  We can verify tomorrow.

**Comment by jrmerz** [comment]
Been working for a month now, going to close.
